version: '3.8'

services:

  app:
    build: .
    container_name: loomi-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-service:5432/order
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=post
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=redpanda:9092
    depends_on:
      postgres-service:
        condition: service_healthy
      redpanda:
        condition: service_healthy
    networks:
      - loomi-network


  postgres-service:
    image: postgres:15-alpine
    container_name: loomi-db
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=post
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d order"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - loomi-network


  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: loomi-broker
    command:
      - redpanda start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
    ports:
      - "18081:18081"
      - "18082:18082"
      - "19092:19092"
      - "9644:9644"
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -q 'Healthy'"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - loomi-network

volumes:
  postgres_data:
  redpanda_data:

networks:
  loomi-network:
    driver: bridge